// Code generated by "stringer -type=StackoType"; DO NOT EDIT.

package stackoval

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StackoString-0]
	_ = x[StackoInt-1]
	_ = x[StackoFloat-2]
	_ = x[StackoWord-3]
	_ = x[StackoList-4]
	_ = x[StackoSymbol-5]
	_ = x[StackoBool-6]
}

const _StackoType_name = "StackoStringStackoIntStackoFloatStackoWordStackoListStackoSymbolStackoBool"

var _StackoType_index = [...]uint8{0, 12, 21, 32, 42, 52, 64, 74}

func (i StackoType) String() string {
	if i < 0 || i >= StackoType(len(_StackoType_index)-1) {
		return "StackoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StackoType_name[_StackoType_index[i]:_StackoType_index[i+1]]
}
